---
linters:
  enable-all: true
  disable:
    - exportloopref
    - gofumpt

linters-settings:
  depguard:
    rules:
      main:
        allow:
          - log
          - os
          - fmt
          - strings
          - unicode
          - errors
          - path/filepath
          - embed
          - time
          - strconv
          - slices
          - sort
          - regexp
          - encoding/json
          - testing
          - gopkg.in/yaml.v3
          - github.com/spf13/cobra
          - github.com/xeipuuv/gojsonschema
          - github.com/servletcloud/Andmerada/internal/osutil
          - github.com/servletcloud/Andmerada/internal/project
          - github.com/servletcloud/Andmerada/internal/cmd
          - github.com/servletcloud/Andmerada/internal/resources
          - github.com/servletcloud/Andmerada/internal/schema
          - github.com/stretchr/testify/assert
          - github.com/stretchr/testify/require
          - github.com/servletcloud/Andmerada/internal/source
          - github.com/servletcloud/Andmerada/internal/tests
          - github.com/servletcloud/Andmerada/internal/ymlutil
