name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract Go Version from go.mod
        id: get-go-version
        run: echo "go-version=$(grep '^go ' go.mod | cut -d' ' -f2)" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go-version }}

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: run

      - name: Install Make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Run CI
        run: make ci
